use std::fmt::Write;

use super::sql as codegen;
use crate::ast::*;

pub struct ClientOutput {
    pub typescript: String,
    pub rust: String,
}

pub fn generate_client(program: &Program) -> ClientOutput {
    let codegen_result = codegen::generate(program);
    ClientOutput {
        typescript: gen_ts_client(program, &codegen_result),
        rust: gen_rust_client(program, &codegen_result),
    }
}

fn gen_ts_client(program: &Program, codegen_result: &codegen::CodegenResult) -> String {
    let mut out = String::new();
    writeln!(out, "// Generated by Axis compiler — do not edit").unwrap();
    writeln!(out, "// TypeScript API client").unwrap();
    writeln!(out).unwrap();

    for c in &program.constructs {
        if let Construct::Shape(shape) = c {
            writeln!(out, "export interface {} {{", shape.name).unwrap();
            for field in &shape.fields {
                let optional = matches!(&field.ty, TypeExpr::Maybe(_));
                let ty = ts_type(&field.ty);
                let opt = if optional { "?" } else { "" };
                writeln!(out, "  {}{}: {};", field.name, opt, ty).unwrap();
            }
            writeln!(out, "}}").unwrap();
            writeln!(out).unwrap();
        }
    }

    for c in &program.constructs {
        if let Construct::Flow(flow) = c {
            if let Some(body) = &flow.body {
                writeln!(out, "export interface {}Input {{", pascal(&flow.name)).unwrap();
                for field in &body.fields {
                    let ty = ts_type(&field.ty);
                    let required = field
                        .modifiers
                        .iter()
                        .any(|m| matches!(m, Modifier::Required));
                    let opt = if required { "" } else { "?" };
                    writeln!(out, "  {}{}: {};", field.name, opt, ty).unwrap();
                }
                writeln!(out, "}}").unwrap();
                writeln!(out).unwrap();
            }
        }
    }

    writeln!(out, "export interface ApiError {{").unwrap();
    writeln!(out, "  error: string;").unwrap();
    writeln!(out, "  status: number;").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "export class AxisClient {{").unwrap();
    writeln!(out, "  private baseUrl: string;").unwrap();
    writeln!(out, "  private headers: Record<string, string>;").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "  constructor(baseUrl: string, headers: Record<string, string> = {{}}) {{"
    )
    .unwrap();
    writeln!(out, "    this.baseUrl = baseUrl.replace(/\\/$/, '');").unwrap();
    writeln!(
        out,
        "    this.headers = {{ 'Content-Type': 'application/json', ...headers }};"
    )
    .unwrap();
    writeln!(out, "  }}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "  private async request<T>(method: string, path: string, body?: unknown, headers: Record<string, string> = {{}}): Promise<T> {{").unwrap();
    writeln!(
        out,
        "    const res = await fetch(`${{this.baseUrl}}${{path}}`, {{"
    )
    .unwrap();
    writeln!(out, "      method,").unwrap();
    writeln!(out, "      headers: {{ ...this.headers, ...headers }},").unwrap();
    writeln!(out, "      body: body ? JSON.stringify(body) : undefined,").unwrap();
    writeln!(out, "    }});").unwrap();
    writeln!(out, "    if (!res.ok) {{").unwrap();
    writeln!(
        out,
        "      const err = await res.json().catch(() => ({{ error: res.statusText }}));"
    )
    .unwrap();
    writeln!(
        out,
        "      throw {{ ...err, status: res.status }} as ApiError;"
    )
    .unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "    return res.json();").unwrap();
    writeln!(out, "  }}").unwrap();
    writeln!(out).unwrap();

    for route in &codegen_result.routes {
        let flow = program.constructs.iter().find_map(|c| {
            if let Construct::Flow(f) = c {
                if f.name == route.name { Some(f) } else { None }
            } else {
                None
            }
        });
        let Some(flow) = flow else { continue };

        let return_type = flow
            .return_stmt
            .body
            .as_ref()
            .map(|b| match b {
                ReturnBody::Binding(name) => infer_return_type(name, flow, program),
                ReturnBody::Inline(_) => "any".to_string(),
                ReturnBody::Paginated { .. } => {
                    "{ items: any[]; total: number; cursor: string; has_more: boolean }".to_string()
                }
            })
            .unwrap_or_else(|| "void".to_string());

        let path_params: Vec<&str> = flow
            .path
            .split('/')
            .filter(|s| s.starts_with(':'))
            .map(|s| s.trim_start_matches(':'))
            .collect();

        let has_body = matches!(route.method.as_str(), "POST" | "PUT" | "PATCH");
        let input_type = if has_body {
            Some(format!("{}Input", pascal(&flow.name)))
        } else {
            None
        };

        let mut params: Vec<String> = path_params.iter().map(|p| format!("{p}: string")).collect();
        if let Some(ref it) = input_type {
            params.push(format!("body: {it}"));
        }
        if flow.idempotency.is_some() {
            params.push("idempotencyKey: string".into());
        }

        let method_name = camel(&flow.name);
        writeln!(
            out,
            "  async {method_name}({}): Promise<{return_type}> {{",
            params.join(", ")
        )
        .unwrap();

        let path_str = flow
            .path
            .split('/')
            .map(|seg| {
                if let Some(name) = seg.strip_prefix(':') {
                    format!("${{{name}}}")
                } else {
                    seg.to_string()
                }
            })
            .collect::<Vec<_>>()
            .join("/");

        let body_arg = if has_body { "body" } else { "undefined" };
        let header_arg = flow
            .idempotency
            .as_ref()
            .map(|declaration| {
                let header = declaration
                    .key
                    .segments
                    .get(1)
                    .map(|name| name.replace('_', "-"))
                    .unwrap_or_else(|| "idempotency-key".into());
                format!(", {{ '{header}': idempotencyKey }}")
            })
            .unwrap_or_default();
        writeln!(
            out,
            "    return this.request<{return_type}>('{}', `{path_str}`, {body_arg}{header_arg});",
            route.method
        )
        .unwrap();
        writeln!(out, "  }}").unwrap();
        writeln!(out).unwrap();
    }

    writeln!(out, "}}").unwrap();

    out
}

fn gen_rust_client(program: &Program, codegen_result: &codegen::CodegenResult) -> String {
    let mut out = String::new();
    writeln!(out, "// Generated by Axis compiler — do not edit").unwrap();
    writeln!(out, "// Rust API client").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "use serde::{{Deserialize, Serialize}};").unwrap();
    writeln!(out).unwrap();

    for c in &program.constructs {
        if let Construct::Shape(shape) = c {
            writeln!(out, "#[derive(Debug, Clone, Serialize, Deserialize)]").unwrap();
            writeln!(out, "pub struct {} {{", shape.name).unwrap();
            for field in &shape.fields {
                let ty = rust_type(&field.ty);
                writeln!(out, "    pub {}: {},", field.name, ty).unwrap();
            }
            writeln!(out, "}}").unwrap();
            writeln!(out).unwrap();
        }
    }

    for c in &program.constructs {
        if let Construct::Flow(flow) = c {
            if let Some(body) = &flow.body {
                writeln!(out, "#[derive(Debug, Clone, Serialize)]").unwrap();
                writeln!(out, "pub struct {}Input {{", pascal(&flow.name)).unwrap();
                for field in &body.fields {
                    let ty = rust_type(&field.ty);
                    writeln!(out, "    pub {}: {},", field.name, ty).unwrap();
                }
                writeln!(out, "}}").unwrap();
                writeln!(out).unwrap();
            }
        }
    }

    writeln!(out, "pub struct AxisClient {{").unwrap();
    writeln!(out, "    base_url: String,").unwrap();
    writeln!(out, "    client: reqwest::Client,").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "impl AxisClient {{").unwrap();
    writeln!(out, "    pub fn new(base_url: &str) -> Self {{").unwrap();
    writeln!(out, "        Self {{").unwrap();
    writeln!(
        out,
        "            base_url: base_url.trim_end_matches('/').to_string(),"
    )
    .unwrap();
    writeln!(out, "            client: reqwest::Client::new(),").unwrap();
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out).unwrap();

    for route in &codegen_result.routes {
        let flow = program.constructs.iter().find_map(|c| {
            if let Construct::Flow(f) = c {
                if f.name == route.name { Some(f) } else { None }
            } else {
                None
            }
        });
        let Some(flow) = flow else { continue };

        let return_type = flow
            .return_stmt
            .body
            .as_ref()
            .map(|b| match b {
                ReturnBody::Binding(name) => infer_rust_return_type(name, flow, program),
                ReturnBody::Inline(_) | ReturnBody::Paginated { .. } => {
                    "serde_json::Value".to_string()
                }
            })
            .unwrap_or_else(|| "()".to_string());

        let path_params: Vec<&str> = flow
            .path
            .split('/')
            .filter(|s| s.starts_with(':'))
            .map(|s| s.trim_start_matches(':'))
            .collect();

        let has_body = matches!(route.method.as_str(), "POST" | "PUT" | "PATCH");

        let mut params: Vec<String> = vec!["&self".into()];
        for p in &path_params {
            params.push(format!("{p}: &str"));
        }
        if has_body {
            params.push(format!("body: &{}Input", pascal(&flow.name)));
        }
        if flow.idempotency.is_some() {
            params.push("idempotency_key: &str".into());
        }

        let method = route.method.to_lowercase();
        writeln!(
            out,
            "    pub async fn {}({}) -> Result<{return_type}, reqwest::Error> {{",
            snake(&flow.name),
            params.join(", ")
        )
        .unwrap();

        let path_str = flow
            .path
            .split('/')
            .map(|seg| {
                if let Some(name) = seg.strip_prefix(':') {
                    format!("{{{name}}}")
                } else {
                    seg.to_string()
                }
            })
            .collect::<Vec<_>>()
            .join("/");

        writeln!(
            out,
            "        let url = format!(\"{{}}/{path_str}\", self.base_url{});",
            path_params
                .iter()
                .map(|p| format!(", {p} = {p}"))
                .collect::<String>()
        )
        .unwrap();

        writeln!(out, "        let request = self.client.{method}(&url);").unwrap();
        if has_body {
            writeln!(out, "        let request = request.json(body);").unwrap();
        }
        if let Some(declaration) = &flow.idempotency {
            let header = declaration
                .key
                .segments
                .get(1)
                .map(|name| name.replace('_', "-"))
                .unwrap_or_else(|| "idempotency-key".into());
            writeln!(
                out,
                "        let request = request.header(\"{header}\", idempotency_key);"
            )
            .unwrap();
        }
        writeln!(out, "        request.send().await?.json().await").unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out).unwrap();
    }

    writeln!(out, "}}").unwrap();

    out
}

fn infer_return_type(binding: &str, flow: &FlowDef, program: &Program) -> String {
    for step in &flow.steps {
        if let FlowStep::Let(l) = step {
            if l.name == binding {
                return match &l.expr {
                    Expr::Fetch { source, .. } => {
                        shape_name_for_source(source, program).unwrap_or("any".into())
                    }
                    Expr::Query { source, .. } => {
                        let shape = shape_name_for_source(source, program).unwrap_or("any".into());
                        format!("{shape}[]")
                    }
                    _ => "any".into(),
                };
            }
        }
        if let FlowStep::Insert(i) = step {
            if i.binding.as_deref() == Some(binding) {
                return shape_name_for_source(&i.source, program).unwrap_or("any".into());
            }
        }
        if let FlowStep::Upsert(upsert) = step {
            if upsert.binding.as_deref() == Some(binding) {
                return shape_name_for_source(&upsert.source, program).unwrap_or("any".into());
            }
        }
    }
    "any".into()
}

fn infer_rust_return_type(binding: &str, flow: &FlowDef, program: &Program) -> String {
    for step in &flow.steps {
        if let FlowStep::Let(l) = step {
            if l.name == binding {
                return match &l.expr {
                    Expr::Fetch { source, .. } => {
                        shape_name_for_source(source, program).unwrap_or("serde_json::Value".into())
                    }
                    Expr::Query { source, .. } => {
                        let shape = shape_name_for_source(source, program)
                            .unwrap_or("serde_json::Value".into());
                        format!("Vec<{shape}>")
                    }
                    _ => "serde_json::Value".into(),
                };
            }
        }
        if let FlowStep::Insert(i) = step {
            if i.binding.as_deref() == Some(binding) {
                return shape_name_for_source(&i.source, program)
                    .unwrap_or("serde_json::Value".into());
            }
        }
        if let FlowStep::Upsert(upsert) = step {
            if upsert.binding.as_deref() == Some(binding) {
                return shape_name_for_source(&upsert.source, program)
                    .unwrap_or("serde_json::Value".into());
            }
        }
    }
    "serde_json::Value".into()
}

fn shape_name_for_source(source_name: &str, program: &Program) -> Option<String> {
    program.constructs.iter().find_map(|c| {
        if let Construct::Source(s) = c {
            if s.name == source_name {
                Some(s.shape.clone())
            } else {
                None
            }
        } else {
            None
        }
    })
}

fn ts_type(ty: &TypeExpr) -> String {
    match ty {
        TypeExpr::Uuid
        | TypeExpr::String(_)
        | TypeExpr::Text
        | TypeExpr::Date
        | TypeExpr::Timestamp => "string".into(),
        TypeExpr::Int { .. } | TypeExpr::Decimal { .. } => "number".into(),
        TypeExpr::Bool => "boolean".into(),
        TypeExpr::Json => "any".into(),
        TypeExpr::Enum(variants) => variants
            .iter()
            .map(|v| format!("'{v}'"))
            .collect::<Vec<_>>()
            .join(" | "),
        TypeExpr::List(inner) => format!("{}[]", ts_type(inner)),
        TypeExpr::Maybe(inner) => format!("{} | null", ts_type(inner)),
        TypeExpr::Map(_, v) => format!("Record<string, {}>", ts_type(v)),
        TypeExpr::Blob => "Blob".into(),
        TypeExpr::Ref { shape, .. } => shape.clone(),
    }
}

fn rust_type(ty: &TypeExpr) -> String {
    match ty {
        TypeExpr::Uuid => "uuid::Uuid".into(),
        TypeExpr::String(_) | TypeExpr::Text => "String".into(),
        TypeExpr::Int { .. } => "i64".into(),
        TypeExpr::Decimal { .. } => "rust_decimal::Decimal".into(),
        TypeExpr::Bool => "bool".into(),
        TypeExpr::Date | TypeExpr::Timestamp => "chrono::DateTime<chrono::Utc>".into(),
        TypeExpr::Json => "serde_json::Value".into(),
        TypeExpr::Enum(_) => "String".into(),
        TypeExpr::List(inner) => format!("Vec<{}>", rust_type(inner)),
        TypeExpr::Maybe(inner) => format!("Option<{}>", rust_type(inner)),
        TypeExpr::Map(_, v) => format!("std::collections::HashMap<String, {}>", rust_type(v)),
        TypeExpr::Blob => "Vec<u8>".into(),
        TypeExpr::Ref { shape, .. } => shape.clone(),
    }
}

fn pascal(s: &str) -> String {
    s.split('_')
        .map(|w| {
            let mut c = w.chars();
            match c.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().to_string() + &c.as_str().to_lowercase(),
            }
        })
        .collect()
}

fn camel(s: &str) -> String {
    let p = pascal(s);
    let mut c = p.chars();
    match c.next() {
        None => String::new(),
        Some(f) => f.to_lowercase().to_string() + c.as_str(),
    }
}

fn snake(s: &str) -> String {
    s.to_lowercase()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::project::compile_source;

    #[test]
    fn test_ts_client_basic() {
        let input = r#"SHAPE User
  id UUID PK AUTO
  name STRING 100 REQUIRED

SOURCE users POSTGRES
  SHAPE User
  INDEX id

REALM api
  CAPABILITY read users

FLOW get_user get /users/:id
  REALM api
  AUTH session
  LET user
    FETCH users
      FILTER id EQ path.id
    OR 404
  RETURN 200 user
"#;
        let program = compile_source(input).unwrap();
        let client = generate_client(&program);

        assert!(client.typescript.contains("export interface User"));
        assert!(client.typescript.contains("export class AxisClient"));
        assert!(
            client
                .typescript
                .contains("async getUser(id: string): Promise<User>")
        );
        assert!(client.typescript.contains("this.request<User>('GET'"));
    }

    #[test]
    fn test_ts_client_with_body() {
        let input = r#"SHAPE User
  id UUID PK AUTO
  name STRING 100 REQUIRED

SOURCE users POSTGRES
  SHAPE User
  INDEX id

REALM api
  CAPABILITY read users
  CAPABILITY write users

FLOW create_user post /users
  REALM api
  AUTH session
  BODY UserCreate
    name STRING 100 REQUIRED
  INSERT users
    name body.name
  AS user
  RETURN 201 user
"#;
        let program = compile_source(input).unwrap();
        let client = generate_client(&program);

        assert!(
            client
                .typescript
                .contains("export interface CreateUserInput")
        );
        assert!(
            client
                .typescript
                .contains("async createUser(body: CreateUserInput): Promise<User>")
        );
        assert!(client.typescript.contains("'POST'"));
    }

    #[test]
    fn test_ts_client_list_return() {
        let input = r#"SHAPE User
  id UUID PK AUTO
  name STRING 100 REQUIRED

SOURCE users POSTGRES
  SHAPE User
  INDEX id

REALM api
  CAPABILITY read users

FLOW list_users get /users
  REALM api
  AUTH session
  LET users
    QUERY users
  RETURN 200 users
"#;
        let program = compile_source(input).unwrap();
        let client = generate_client(&program);
        assert!(client.typescript.contains("Promise<User[]>"));
    }

    #[test]
    fn test_rust_client_basic() {
        let input = r#"SHAPE User
  id UUID PK AUTO
  name STRING 100 REQUIRED

SOURCE users POSTGRES
  SHAPE User
  INDEX id

REALM api
  CAPABILITY read users

FLOW get_user get /users/:id
  REALM api
  AUTH session
  LET user
    FETCH users
      FILTER id EQ path.id
    OR 404
  RETURN 200 user
"#;
        let program = compile_source(input).unwrap();
        let client = generate_client(&program);

        assert!(client.rust.contains("pub struct User"));
        assert!(client.rust.contains("pub struct AxisClient"));
        assert!(
            client
                .rust
                .contains("pub async fn get_user(&self, id: &str) -> Result<User, reqwest::Error>")
        );
    }

    #[test]
    fn test_rust_client_with_body() {
        let input = r#"SHAPE User
  id UUID PK AUTO
  name STRING 100 REQUIRED

SOURCE users POSTGRES
  SHAPE User
  INDEX id

REALM api
  CAPABILITY read users
  CAPABILITY write users

FLOW create_user post /users
  REALM api
  AUTH session
  BODY UserCreate
    name STRING 100 REQUIRED
  INSERT users
    name body.name
  AS user
  RETURN 201 user
"#;
        let program = compile_source(input).unwrap();
        let client = generate_client(&program);

        assert!(client.rust.contains("pub struct CreateUserInput"));
        assert!(client.rust.contains("body: &CreateUserInput"));
        assert!(client.rust.contains(".json(body)"));
    }

    #[test]
    fn test_full_example_client() {
        let input = std::fs::read_to_string(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("examples/full.axis"),
        )
        .unwrap();
        let program = compile_source(&input).unwrap();
        let client = generate_client(&program);

        assert!(client.typescript.contains("AxisClient"));
        assert!(client.rust.contains("AxisClient"));
        assert!(client.typescript.contains("listOrders"));
        assert!(client.rust.contains("list_orders"));
    }

    #[test]
    fn test_idempotent_clients_require_operation_key() {
        let program =
            compile_source(include_str!("../../examples/messenger-primitives.axis")).unwrap();
        let client = generate_client(&program);
        assert!(client.typescript.contains("idempotencyKey: string"));
        assert!(
            client
                .typescript
                .contains("{ 'idempotency-key': idempotencyKey }")
        );
        assert!(client.rust.contains("idempotency_key: &str"));
        assert!(
            client
                .rust
                .contains("request.header(\"idempotency-key\", idempotency_key)")
        );
    }
}
