use std::fmt::Write;

use crate::ast::*;
use crate::codegens::sql as codegen;

pub fn generate_graphql(program: &Program) -> String {
    let codegen_result = codegen::generate(program);
    let mut out = String::new();

    writeln!(out, "# Generated by Axis compiler — do not edit").unwrap();
    writeln!(out).unwrap();

    for c in &program.constructs {
        if let Construct::Shape(shape) = c {
            generate_type(&mut out, shape);
        }
    }

    for c in &program.constructs {
        if let Construct::Flow(flow) = c {
            if let Some(body) = &flow.body {
                writeln!(out, "input {}Input {{", pascal(&flow.name)).unwrap();
                for field in &body.fields {
                    let ty = gql_type(&field.ty);
                    let required = field.modifiers.iter().any(|m| matches!(m, Modifier::Required));
                    let bang = if required { "!" } else { "" };
                    writeln!(out, "  {}: {ty}{bang}", field.name).unwrap();
                }
                writeln!(out, "}}").unwrap();
                writeln!(out).unwrap();
            }
        }
    }

    let queries: Vec<&FlowDef> = program.constructs.iter().filter_map(|c| {
        if let Construct::Flow(f) = c {
            let route = codegen_result.routes.iter().find(|r| r.name == f.name)?;
            if route.method == "GET" { Some(f) } else { None }
        } else {
            None
        }
    }).collect();

    let mutations: Vec<&FlowDef> = program.constructs.iter().filter_map(|c| {
        if let Construct::Flow(f) = c {
            let route = codegen_result.routes.iter().find(|r| r.name == f.name)?;
            if route.method != "GET" { Some(f) } else { None }
        } else {
            None
        }
    }).collect();

    if !queries.is_empty() {
        writeln!(out, "type Query {{").unwrap();
        for flow in &queries {
            generate_field(&mut out, flow, program);
        }
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }

    if !mutations.is_empty() {
        writeln!(out, "type Mutation {{").unwrap();
        for flow in &mutations {
            generate_field(&mut out, flow, program);
        }
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }

    let subscriptions: Vec<&StreamDef> = program.constructs.iter().filter_map(|c| {
        if let Construct::Stream(s) = c { Some(s) } else { None }
    }).collect();

    if !subscriptions.is_empty() {
        writeln!(out, "type Subscription {{").unwrap();
        for stream in &subscriptions {
            for event in &stream.events {
                let ty = pascal(&event.name);
                writeln!(out, "  {}: {ty}", camel(&event.name)).unwrap();
            }
        }
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();

        for stream in &subscriptions {
            for event in &stream.events {
                writeln!(out, "type {} {{", pascal(&event.name)).unwrap();
                for field in &event.fields {
                    writeln!(out, "  {}: {}", field.name, gql_type(&field.ty)).unwrap();
                }
                writeln!(out, "}}").unwrap();
                writeln!(out).unwrap();
            }
        }
    }

    out
}

fn generate_type(out: &mut String, shape: &ShapeDef) {
    writeln!(out, "type {} {{", shape.name).unwrap();
    for field in &shape.fields {
        let ty = gql_type(&field.ty);
        let required = field.modifiers.iter().any(|m| matches!(m, Modifier::Required | Modifier::Pk));
        let bang = if required { "!" } else { "" };
        writeln!(out, "  {}: {ty}{bang}", field.name).unwrap();
    }
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

fn generate_field(out: &mut String, flow: &FlowDef, program: &Program) {
    let path_params: Vec<&str> = flow.path.split('/')
        .filter(|s| s.starts_with(':'))
        .map(|s| s.trim_start_matches(':'))
        .collect();

    let return_type = flow.return_stmt.body.as_ref().map(|b| match b {
        ReturnBody::Binding(name) => infer_gql_return(name, flow, program),
        ReturnBody::Inline(_) => "JSON".into(),
        ReturnBody::Paginated { .. } => format!("{}Connection", pascal(&flow.name)),
    }).unwrap_or("Boolean".into());

    let has_body = flow.body.is_some();

    let mut params = Vec::new();
    for p in &path_params {
        params.push(format!("{p}: ID!"));
    }
    if has_body {
        params.push(format!("input: {}Input!", pascal(&flow.name)));
    }

    let param_str = if params.is_empty() {
        String::new()
    } else {
        format!("({})", params.join(", "))
    };

    writeln!(out, "  {}{param_str}: {return_type}", camel(&flow.name)).unwrap();
}

fn infer_gql_return(binding: &str, flow: &FlowDef, program: &Program) -> String {
    for step in &flow.steps {
        if let FlowStep::Let(l) = step {
            if l.name == binding {
                return match &l.expr {
                    Expr::Fetch { source, .. } => shape_for_source(source, program),
                    Expr::Query { source, .. } => format!("[{}!]!", shape_for_source(source, program)),
                    _ => "JSON".into(),
                };
            }
        }
        if let FlowStep::Insert(i) = step {
            if i.binding.as_deref() == Some(binding) {
                return shape_for_source(&i.source, program);
            }
        }
    }
    "JSON".into()
}

fn shape_for_source(source: &str, program: &Program) -> String {
    program.constructs.iter().find_map(|c| {
        if let Construct::Source(s) = c {
            if s.name == source { Some(s.shape.clone()) } else { None }
        } else {
            None
        }
    }).unwrap_or("JSON".into())
}

fn gql_type(ty: &TypeExpr) -> String {
    match ty {
        TypeExpr::Uuid => "ID".into(),
        TypeExpr::String(_) | TypeExpr::Text => "String".into(),
        TypeExpr::Int { .. } => "Int".into(),
        TypeExpr::Decimal { .. } => "Float".into(),
        TypeExpr::Bool => "Boolean".into(),
        TypeExpr::Date | TypeExpr::Timestamp => "String".into(),
        TypeExpr::Json => "JSON".into(),
        TypeExpr::Enum(variants) => {
            if variants.is_empty() { return "String".into(); }
            pascal(&variants[0]) + "Enum"
        }
        TypeExpr::List(inner) => format!("[{}]", gql_type(inner)),
        TypeExpr::Maybe(inner) => gql_type(inner),
        TypeExpr::Blob => "String".into(),
        TypeExpr::Map(_, _) => "JSON".into(),
        TypeExpr::Ref { shape, .. } => shape.clone(),
    }
}

fn pascal(s: &str) -> String {
    s.split('_').map(|w| {
        let mut c = w.chars();
        match c.next() {
            None => String::new(),
            Some(f) => f.to_uppercase().to_string() + &c.as_str().to_lowercase(),
        }
    }).collect()
}

fn camel(s: &str) -> String {
    let p = pascal(s);
    let mut c = p.chars();
    match c.next() {
        None => String::new(),
        Some(f) => f.to_lowercase().to_string() + c.as_str(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::project::compile_source;

    #[test]
    fn test_graphql_basic() {
        let input = r#"SHAPE User
  id UUID PK AUTO
  name STRING 100 REQUIRED
  active BOOL

SOURCE users POSTGRES
  SHAPE User
  INDEX id

REALM api
  CAPABILITY read users

FLOW get_user get /users/:id
  REALM api
  AUTH session
  LET user
    FETCH users
      FILTER id EQ path.id
    OR 404
  RETURN 200 user

FLOW list_users get /users
  REALM api
  AUTH session
  LET users
    QUERY users
  RETURN 200 users
"#;
        let program = compile_source(input).unwrap();
        let schema = generate_graphql(&program);

        assert!(schema.contains("type User {"));
        assert!(schema.contains("id: ID!"));
        assert!(schema.contains("name: String!"));
        assert!(schema.contains("type Query {"));
        assert!(schema.contains("getUser(id: ID!): User"));
        assert!(schema.contains("listUsers: [User!]!"));
    }

    #[test]
    fn test_graphql_mutations() {
        let input = r#"SHAPE User
  id UUID PK AUTO
  name STRING 100 REQUIRED

SOURCE users POSTGRES
  SHAPE User
  INDEX id

REALM api
  CAPABILITY read users
  CAPABILITY write users

FLOW create_user post /users
  REALM api
  AUTH session
  BODY UserCreate
    name STRING 100 REQUIRED
  INSERT users
    name body.name
  AS user
  RETURN 201 user
"#;
        let program = compile_source(input).unwrap();
        let schema = generate_graphql(&program);

        assert!(schema.contains("input CreateUserInput {"));
        assert!(schema.contains("name: String!"));
        assert!(schema.contains("type Mutation {"));
        assert!(schema.contains("createUser(input: CreateUserInput!): User"));
    }

    #[test]
    fn test_graphql_subscriptions() {
        let input = r#"SHAPE User
  id UUID PK AUTO

SOURCE users POSTGRES
  SHAPE User
  INDEX id

STREAM updates ws /ws/updates
  EVENT user_online
    user_id UUID
  EVENT user_offline
    user_id UUID
"#;
        let program = compile_source(input).unwrap();
        let schema = generate_graphql(&program);

        assert!(schema.contains("type Subscription {"));
        assert!(schema.contains("userOnline: UserOnline"));
        assert!(schema.contains("type UserOnline {"));
        assert!(schema.contains("user_id: ID"));
    }

    #[test]
    fn test_graphql_full_example() {
        let input = std::fs::read_to_string(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("examples/full.axis")
        ).unwrap();
        let program = compile_source(&input).unwrap();
        let schema = generate_graphql(&program);

        assert!(schema.contains("type Query {"));
        assert!(schema.contains("type Mutation {"));
        assert!(schema.contains("type Order {"));
    }

    #[test]
    fn test_graphql_enum_types() {
        let input = r#"SHAPE User
  id UUID PK AUTO
  status ENUM active inactive banned

SOURCE users POSTGRES
  SHAPE User
  INDEX id
"#;
        let program = compile_source(input).unwrap();
        let schema = generate_graphql(&program);
        assert!(schema.contains("type User {"));
    }
}
