use std::fmt;

#[derive(Debug, Clone, PartialEq)]
pub struct Token {
    pub kind: TokenKind,
    pub span: Span,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Span {
    pub offset: usize,
    pub len: usize,
    pub line: usize,
    pub col: usize,
}

#[derive(Debug, Clone, PartialEq)]
pub enum TokenKind {
    // Structure
    Indent,
    Dedent,
    Newline,

    // Identifiers and literals
    Ident(String),
    ShapeName(String),
    IntLit(i64),
    DecimalLit(String),
    StringLit(String),
    Path(String),

    // Construct keywords
    Shape,
    Source,
    Realm,
    Flow,
    Saga,
    Surface,
    Migrate,
    Policy,
    Service,
    Storage,

    // Source types
    Postgres,
    Mysql,
    Sqlite,
    Redis,
    Elasticsearch,
    Dynamodb,

    // Flow keywords
    Auth,
    Body,
    Param,
    Header,
    Rule,
    Guard,
    Let,
    Fetch,
    Query,
    Insert,
    Update,
    Delete,
    Call,
    Effect,
    Match,
    When,
    Default,
    Return,
    Limit,
    Cache,
    Scope,
    Require,

    // Expression keywords
    Filter,
    Sort,
    Asc,
    Desc,
    Cursor,
    PageSize,
    Or,
    And,
    Not,
    If,
    Then,
    Else,
    Eq,
    Neq,
    Gt,
    Gte,
    Lt,
    Lte,
    In,
    Between,
    Like,
    Empty,
    Exists,
    Add,
    Sub,
    Mul,
    Div,
    Mod,
    Round,
    Ceil,
    Floor,
    Abs,
    Count,
    Sum,
    Avg,
    Min,
    Max,
    First,
    Last,
    Concat,
    Lower,
    Upper,
    Trim,
    Substring,
    Length,
    StartsWith,
    EndsWith,
    Contains,
    DaysBetween,
    HoursBetween,
    MinutesBetween,
    Now,
    NowPlus,
    NowMinus,
    FormatDate,
    Coalesce,
    Literal,
    ToInt,
    ToDecimal,
    ToString_,

    // Type keywords
    Uuid,
    String_,
    Text,
    Int,
    Decimal,
    Bool,
    Date,
    Timestamp,
    Enum,
    Ref,
    List,
    Map,
    Json,
    Maybe,

    // Modifier keywords
    Pk,
    Auto,
    Required,
    Unique,
    Precision,
    Scale,

    // Other keywords
    Index,
    Tenant,
    Capability,
    Field,
    Hide,
    Expose,
    Deprecate,
    Route,
    Step,
    Verify,
    Compensate,
    Yield_,
    OnSuccess,
    OnFailure,
    RunCompensations,
    Template,
    Data,
    Task,
    AppliesTo,
    Writes,
    Reads,
    Method,
    Where,
    Set,
    Copy,
    Compute,
    Drop,
    Any,
    None_,
    True_,
    False_,
    Hash,
    Async_,
    Stream,
    Each,
    Reduce,
    Split,
    Replace,
    Func,
    Try,
    Recover,
    Format,
    Select,
    Event,
    Webhook,
    Signature,
    Hmac,
    Items,
    Total,
    NextCursor,
    HasMore,
    As,
    To,
    Rename,
    Sunset,
    BasePath,
    Endpoint,
    Vault,
    Input,
    Output,
    Timeout,
    Retry,
    Backoff,
    Ttl,
    Vary,
    With,
    Parallel,
    Receive,
    On,
    Blob,
    Multipart,
    Render,
    Translate,

    // Storage keywords
    Backend,
    Bucket,
    Prefix,
    Access,
    MaxSize,
    Types,
    Upload,

    // Time units
    Seconds,
    Minutes,
    Hours,
    Days,
    Weeks,
    Months,
    Years,

    // Symbols
    Arrow,   // ->
    Dot,     // .
    Colon,   // :

    // Special
    Eof,
}

impl TokenKind {
    pub fn keyword_str(&self) -> Option<&'static str> {
        match self {
            TokenKind::Shape => Some("SHAPE"),
            TokenKind::Source => Some("SOURCE"),
            TokenKind::Realm => Some("REALM"),
            TokenKind::Flow => Some("FLOW"),
            TokenKind::Saga => Some("SAGA"),
            TokenKind::Surface => Some("SURFACE"),
            TokenKind::Migrate => Some("MIGRATE"),
            TokenKind::Policy => Some("POLICY"),
            TokenKind::Service => Some("SERVICE"),
            TokenKind::Storage => Some("STORAGE"),
            TokenKind::Postgres => Some("POSTGRES"),
            TokenKind::Mysql => Some("MYSQL"),
            TokenKind::Sqlite => Some("SQLITE"),
            TokenKind::Redis => Some("REDIS"),
            TokenKind::Elasticsearch => Some("ELASTICSEARCH"),
            TokenKind::Dynamodb => Some("DYNAMODB"),
            TokenKind::Auth => Some("AUTH"),
            TokenKind::Body => Some("BODY"),
            TokenKind::Param => Some("PARAM"),
            TokenKind::Header => Some("HEADER"),
            TokenKind::Rule => Some("RULE"),
            TokenKind::Guard => Some("GUARD"),
            TokenKind::Let => Some("LET"),
            TokenKind::Fetch => Some("FETCH"),
            TokenKind::Query => Some("QUERY"),
            TokenKind::Insert => Some("INSERT"),
            TokenKind::Update => Some("UPDATE"),
            TokenKind::Delete => Some("DELETE"),
            TokenKind::Call => Some("CALL"),
            TokenKind::Effect => Some("EFFECT"),
            TokenKind::Match => Some("MATCH"),
            TokenKind::When => Some("WHEN"),
            TokenKind::Default => Some("DEFAULT"),
            TokenKind::Return => Some("RETURN"),
            TokenKind::Limit => Some("LIMIT"),
            TokenKind::Cache => Some("CACHE"),
            TokenKind::Scope => Some("SCOPE"),
            TokenKind::Require => Some("REQUIRE"),
            TokenKind::Filter => Some("FILTER"),
            TokenKind::Sort => Some("SORT"),
            TokenKind::Asc => Some("ASC"),
            TokenKind::Desc => Some("DESC"),
            TokenKind::Cursor => Some("CURSOR"),
            TokenKind::PageSize => Some("PAGE_SIZE"),
            TokenKind::Or => Some("OR"),
            TokenKind::And => Some("AND"),
            TokenKind::Not => Some("NOT"),
            TokenKind::If => Some("IF"),
            TokenKind::Eq => Some("EQ"),
            TokenKind::Neq => Some("NEQ"),
            TokenKind::Gt => Some("GT"),
            TokenKind::Gte => Some("GTE"),
            TokenKind::Lt => Some("LT"),
            TokenKind::Lte => Some("LTE"),
            TokenKind::In => Some("IN"),
            TokenKind::Between => Some("BETWEEN"),
            TokenKind::Like => Some("LIKE"),
            TokenKind::Empty => Some("EMPTY"),
            TokenKind::Exists => Some("EXISTS"),
            TokenKind::Add => Some("ADD"),
            TokenKind::Sub => Some("SUB"),
            TokenKind::Mul => Some("MUL"),
            TokenKind::Div => Some("DIV"),
            TokenKind::Mod => Some("MOD"),
            TokenKind::Round => Some("ROUND"),
            TokenKind::Ceil => Some("CEIL"),
            TokenKind::Floor => Some("FLOOR"),
            TokenKind::Abs => Some("ABS"),
            TokenKind::Count => Some("COUNT"),
            TokenKind::Sum => Some("SUM"),
            TokenKind::Avg => Some("AVG"),
            TokenKind::Min => Some("MIN"),
            TokenKind::Max => Some("MAX"),
            TokenKind::First => Some("FIRST"),
            TokenKind::Last => Some("LAST"),
            TokenKind::Concat => Some("CONCAT"),
            TokenKind::Lower => Some("LOWER"),
            TokenKind::Upper => Some("UPPER"),
            TokenKind::Trim => Some("TRIM"),
            TokenKind::Substring => Some("SUBSTRING"),
            TokenKind::Length => Some("LENGTH"),
            TokenKind::StartsWith => Some("STARTS_WITH"),
            TokenKind::EndsWith => Some("ENDS_WITH"),
            TokenKind::Contains => Some("CONTAINS"),
            TokenKind::DaysBetween => Some("DAYS_BETWEEN"),
            TokenKind::HoursBetween => Some("HOURS_BETWEEN"),
            TokenKind::MinutesBetween => Some("MINUTES_BETWEEN"),
            TokenKind::Now => Some("NOW"),
            TokenKind::NowPlus => Some("NOW_PLUS"),
            TokenKind::NowMinus => Some("NOW_MINUS"),
            TokenKind::FormatDate => Some("FORMAT_DATE"),
            TokenKind::Coalesce => Some("COALESCE"),
            TokenKind::ToInt => Some("TO_INT"),
            TokenKind::ToDecimal => Some("TO_DECIMAL"),
            TokenKind::ToString_ => Some("TO_STRING"),
            TokenKind::Uuid => Some("UUID"),
            TokenKind::String_ => Some("STRING"),
            TokenKind::Text => Some("TEXT"),
            TokenKind::Int => Some("INT"),
            TokenKind::Decimal => Some("DECIMAL"),
            TokenKind::Bool => Some("BOOL"),
            TokenKind::Date => Some("DATE"),
            TokenKind::Timestamp => Some("TIMESTAMP"),
            TokenKind::Enum => Some("ENUM"),
            TokenKind::Ref => Some("REF"),
            TokenKind::List => Some("LIST"),
            TokenKind::Map => Some("MAP"),
            TokenKind::Json => Some("JSON"),
            TokenKind::Maybe => Some("MAYBE"),
            TokenKind::Pk => Some("PK"),
            TokenKind::Auto => Some("AUTO"),
            TokenKind::Required => Some("REQUIRED"),
            TokenKind::Unique => Some("UNIQUE"),
            TokenKind::Precision => Some("PRECISION"),
            TokenKind::Scale => Some("SCALE"),
            TokenKind::Index => Some("INDEX"),
            TokenKind::Tenant => Some("TENANT"),
            TokenKind::Capability => Some("CAPABILITY"),
            TokenKind::Field => Some("FIELD"),
            TokenKind::Hide => Some("HIDE"),
            TokenKind::Expose => Some("EXPOSE"),
            TokenKind::Deprecate => Some("DEPRECATE"),
            TokenKind::Route => Some("ROUTE"),
            TokenKind::Step => Some("STEP"),
            TokenKind::Verify => Some("VERIFY"),
            TokenKind::Compensate => Some("COMPENSATE"),
            TokenKind::Yield_ => Some("YIELD"),
            TokenKind::OnSuccess => Some("ON_SUCCESS"),
            TokenKind::OnFailure => Some("ON_FAILURE"),
            TokenKind::Template => Some("TEMPLATE"),
            TokenKind::Data => Some("DATA"),
            TokenKind::Task => Some("TASK"),
            TokenKind::AppliesTo => Some("APPLIES_TO"),
            TokenKind::Writes => Some("WRITES"),
            TokenKind::Reads => Some("READS"),
            TokenKind::Method => Some("METHOD"),
            TokenKind::Where => Some("WHERE"),
            TokenKind::Set => Some("SET"),
            TokenKind::Copy => Some("COPY"),
            TokenKind::Compute => Some("COMPUTE"),
            TokenKind::Drop => Some("DROP"),
            TokenKind::None_ => Some("NONE"),
            TokenKind::True_ => Some("TRUE"),
            TokenKind::False_ => Some("FALSE"),
            TokenKind::As => Some("AS"),
            TokenKind::To => Some("TO"),
            TokenKind::Rename => Some("RENAME"),
            TokenKind::Sunset => Some("SUNSET"),
            TokenKind::BasePath => Some("BASE_PATH"),
            TokenKind::Endpoint => Some("ENDPOINT"),
            TokenKind::Vault => Some("VAULT"),
            TokenKind::Input => Some("INPUT"),
            TokenKind::Output => Some("OUTPUT"),
            TokenKind::Timeout => Some("TIMEOUT"),
            TokenKind::Retry => Some("RETRY"),
            TokenKind::Backoff => Some("BACKOFF"),
            TokenKind::Ttl => Some("TTL"),
            TokenKind::Vary => Some("VARY"),
            TokenKind::With => Some("WITH"),
            TokenKind::Parallel => Some("PARALLEL"),
            TokenKind::Receive => Some("RECEIVE"),
            TokenKind::On => Some("ON"),
            TokenKind::Blob => Some("BLOB"),
            TokenKind::Multipart => Some("MULTIPART"),
            TokenKind::Render => Some("RENDER"),
            TokenKind::Translate => Some("T"),
            TokenKind::Backend => Some("BACKEND"),
            TokenKind::Bucket => Some("BUCKET"),
            TokenKind::Prefix => Some("PREFIX"),
            TokenKind::Access => Some("ACCESS"),
            TokenKind::MaxSize => Some("MAX_SIZE"),
            TokenKind::Types => Some("TYPES"),
            TokenKind::Upload => Some("UPLOAD"),
            TokenKind::Stream => Some("STREAM"),
            TokenKind::Each => Some("EACH"),
            TokenKind::Reduce => Some("REDUCE"),
            TokenKind::Split => Some("SPLIT"),
            TokenKind::Replace => Some("REPLACE"),
            TokenKind::Func => Some("FUNC"),
            TokenKind::Try => Some("TRY"),
            TokenKind::Recover => Some("RECOVER"),
            TokenKind::Format => Some("FORMAT"),
            TokenKind::Select => Some("SELECT"),
            TokenKind::Event => Some("EVENT"),
            TokenKind::Webhook => Some("WEBHOOK"),
            TokenKind::Signature => Some("SIGNATURE"),
            TokenKind::Hmac => Some("HMAC"),
            TokenKind::Dedent => Some("DEDENT"),
            TokenKind::Newline => Some("NEWLINE"),
            TokenKind::Eof => Some("EOF"),
            _ => None,
        }
    }
}

impl fmt::Display for TokenKind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        if let Some(kw) = self.keyword_str() {
            return write!(f, "{kw}");
        }
        match self {
            TokenKind::Ident(s) => write!(f, "{s}"),
            TokenKind::ShapeName(s) => write!(f, "{s}"),
            TokenKind::IntLit(n) => write!(f, "{n}"),
            TokenKind::DecimalLit(s) => write!(f, "{s}"),
            TokenKind::StringLit(s) => write!(f, "\"{s}\""),
            TokenKind::Path(s) => write!(f, "{s}"),
            TokenKind::Arrow => write!(f, "->"),
            TokenKind::Dot => write!(f, "."),
            TokenKind::Colon => write!(f, ":"),
            _ => write!(f, "{self:?}"),
        }
    }
}
